# Generated by Django 5.0.2 on 2024-08-22 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="name",
        ),
    ]
