# Generated by Django 5.0.2 on 2024-09-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passenger", "0001_initial"),
        ("tickets", "0005_remove_ticket_price_ticket_adult_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="ticket",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passenger",
                to="tickets.ticket",
            ),
        ),
    ]
