# Generated by Django 5.0.2 on 2024-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_place", models.CharField(max_length=255)),
                ("arrival_place", models.CharField(max_length=255)),
                ("flight_number", models.CharField(max_length=255)),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                ("departure_date", models.DateField()),
                ("luggage", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
