# Generated by Django 5.0.2 on 2024-09-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("available", "Available"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=15,
            ),
        ),
    ]
