# Generated by Django 5.0.2 on 2024-09-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_flight_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="departure_date",
            field=models.DateTimeField(),
        ),
    ]
