# Generated by Django 5.0.2 on 2024-09-14 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0003_alter_flight_departure_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="connection_flight",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connected_flights",
                to="flights.flight",
            ),
        ),
    ]
