# Generated by Django 5.0.2 on 2024-09-15 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0004_flight_connection_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="connection_flight",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connected_flight",
                to="flights.flight",
            ),
        ),
    ]
