# Generated by Django 5.0.2 on 2024-09-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0005_alter_flight_connection_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="isConnected",
            field=models.BooleanField(default=False),
        ),
    ]
