# Generated by Django 5.0.2 on 2024-09-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0006_flight_isconnected"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="adult_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="flight",
            name="child_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="flight",
            name="infant_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
