# Generated by Django 5.0.2 on 2024-09-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0007_flight_adult_price_flight_child_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="isMain",
            field=models.BooleanField(default=True),
        ),
    ]
