# Generated by Django 5.0.2 on 2024-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0010_alter_flight_adult_price_alter_flight_child_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="isMain",
            field=models.BooleanField(default=False),
        ),
    ]
