# Generated by Django 5.0.2 on 2024-09-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0011_alter_flight_ismain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="isConnected",
            field=models.BooleanField(default=False, verbose_name="conectado"),
        ),
        migrations.AlterField(
            model_name="flight",
            name="isMain",
            field=models.BooleanField(default=False, verbose_name="principal"),
        ),
    ]
