# Generated by Django 5.0.2 on 2024-09-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0012_alter_flight_isconnected_alter_flight_ismain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
