# Generated by Django 5.0.2 on 2024-09-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0013_alter_flight_flight_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="isConnected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="flight",
            name="isMain",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("available", "Available"),
                    ("expired", "Expired"),
                ],
                default="scheduled",
                max_length=15,
            ),
        ),
    ]
