# Generated by Django 5.0.2 on 2024-09-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0014_alter_flight_isconnected_alter_flight_ismain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="airline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
