# Generated by Django 5.0.2 on 2024-09-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0015_flight_airline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="departure_date",
            field=models.DateField(),
        ),
    ]
