# Generated by Django 5.0.2 on 2024-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adjustments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="cover_photos/"),
                ),
                ("whatsapp", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("lapse", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Adjustment",
        ),
    ]
