# Generated by Django 5.0.2 on 2024-09-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adjustments", "0002_setting_delete_adjustment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="photo",
        ),
        migrations.AddField(
            model_name="setting",
            name="role",
            field=models.CharField(
                choices=[("primary", "Primary"), ("secondary", "Secondary")],
                default="primary",
                max_length=20,
            ),
        ),
    ]
