# Generated by Django 5.0.2 on 2024-09-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adjustments", "0003_remove_setting_photo_setting_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="role",
        ),
    ]
