# Generated by Django 5.0.2 on 2024-09-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adjustments", "0004_remove_setting_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="setting",
            old_name="lapse",
            new_name="available_days",
        ),
        migrations.AddField(
            model_name="setting",
            name="unavailable_days",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
