# Generated by Django 5.0.2 on 2024-09-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkins", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="role",
            field=models.CharField(default="CheckIn", max_length=255),
        ),
    ]
