# Generated by Django 5.0.2 on 2024-08-27 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="flights",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="flights.flight"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="ticket_issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Flight",
        ),
    ]
