# Generated by Django 5.0.2 on 2024-09-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_ticket_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
