# Generated by Django 5.0.2 on 2024-09-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_ticket_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("available", "Available"),
                    ("unavailable", "Unavailable"),
                ],
                max_length=15,
            ),
        ),
    ]
