# Generated by Django 5.0.2 on 2024-09-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_ticket_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="price",
        ),
        migrations.AddField(
            model_name="ticket",
            name="adult_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="child_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="infant_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
