# Generated by Django 5.0.2 on 2024-09-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_remove_ticket_price_ticket_adult_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="first_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="ticket",
            name="last_name",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="ticket",
            name="passport",
            field=models.CharField(default="", max_length=40),
        ),
    ]
