# Generated by Django 5.0.2 on 2024-09-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_ticket_first_name_ticket_last_name_ticket_passport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("reserved", "Reserved"), ("expired", "Expired")],
                max_length=15,
            ),
        ),
    ]
