# Generated by Django 5.0.2 on 2024-09-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_remove_ticket_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="airline",
        ),
    ]
